MountDestina_1_MapScripts::
.byte 0

Destinia_EventScript_Grunt1::
	trainerbattle_single TRAINER_DESTINIA_GRUNT_MAGMA1, Destinia_GruntText1_1, Destinia_GruntText1_2
	msgbox Destinia_GruntText1_3, MSGBOX_AUTOCLOSE
	end

Destinia_EventScript_Grunt2::
	trainerbattle_single TRAINER_DESTINIA_GRUNT_AQUA1, Destinia_GruntText2_1, Destinia_GruntText2_2
	msgbox Destinia_GruntText2_3, MSGBOX_AUTOCLOSE
	end

Destinia_GruntText1_1:
	.string "I understand everything our leader\n"
	.string "says. But you know what?\p"
	.string "Doing stuff like digging up a super-\n"
	.string "ancient POKéMON and ripping off\l"
	.string "someone's METEORITE…\p"
	.string "I think we're going a little too far.\n"
	.string "What do you think?$"

Destinia_GruntText1_2:
	.string "Yeah, I think we are doing something\n"
	.string "wrong somehow.$"

Destinia_GruntText1_3:
	.string "You know, losing to you cleared my mind.\p"
	.string "The next time I see our leader,\n"
	.string "I'm going to ask him about what we do.$"

Destinia_GruntText2_1:
	.string "I understand everything our leader\n"
	.string "says. But you know what?\p"
	.string "Doing stuff like digging up a super-\n"
	.string "ancient POKéMON and ripping off\l"
	.string "someone's METEORITE…\p"
	.string "I think we're going a little too far.\n"
	.string "What do you think?$"

Destinia_GruntText2_2:
	.string "Yeah, I think we are doing something\n"
	.string "wrong somehow.$"

Destinia_GruntText2_3:
	.string "You know, losing to you cleared my mind.\p"
	.string "The next time I see our leader,\n"
	.string "I'm going to ask him about what we do.$"

